from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "evals" / "check_image_output_records.py"

spec = importlib.util.spec_from_file_location("check_image_output_records", SCRIPT)
check_image_output_records = importlib.util.module_from_spec(spec)
assert spec.loader is not None
sys.modules["check_image_output_records"] = check_image_output_records
spec.loader.exec_module(check_image_output_records)


def write_records(tmp_path: Path, records: list[dict]) -> Path:
    path = tmp_path / "image_output_records.json"
    path.write_text(json.dumps({"status": "test", "records": records}, indent=2), encoding="utf-8")
    return path


def run_cli(path: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--records", str(path), *args],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def placeholder_record() -> dict:
    return {
        "case_id": "gpt_image_text_rendering",
        "target_model": "gpt-image",
        "model_version": "unknown",
        "adapter_version": "0.11.0",
        "prompt_before": "make a poster with headline Summer Archive",
        "rewritten_prompt": "unknown",
        "skill_output_source": "not_recorded",
        "skill_output_date": "unknown",
        "skill_output_notes": "Placeholder only.",
        "task_type": "text_rendering",
        "generation_params": {},
        "output_image_path": "unknown",
        "image_score": None,
        "task_gate_results": {},
        "human_rater": "unknown",
        "observed_failures": [],
        "revision_prompt": "unknown",
        "final_score": None,
    }


def scored_record() -> dict:
    return {
        "case_id": "gpt_image_text_rendering",
        "target_model": "gpt-image",
        "model_version": "gpt-image-1",
        "adapter_version": "0.11.0",
        "prompt_before": "make a poster with headline Summer Archive",
        "rewritten_prompt": "Create a vintage poster with the exact headline \"Summer Archive\".",
        "skill_output_source": "codex_run",
        "skill_output_date": "2026-05-29",
        "skill_output_notes": "Generated by the skill and copied without manual editing.",
        "task_type": "text_rendering",
        "generation_params": {"size": "1024x1024"},
        "output_image_path": "https://example.com/evals/gpt_image_text_rendering.png",
        "image_score": {
            "text_accuracy": 2,
            "text_layout_legibility": 2,
            "subject_fidelity": 2,
            "composition_match": 1,
            "style_coherence": 2,
            "constraint_handling": 2,
            "model_specific_fit": 2,
            "revision_usefulness": 2,
        },
        "task_gate_results": {
            "text_accuracy": True,
            "text_layout_legibility": True,
        },
        "human_rater": "qa",
        "observed_failures": ["Footer text is slightly too small."],
        "revision_prompt": "Keep the headline exact and enlarge the footer text by 20%.",
        "final_score": 15,
    }


def test_placeholder_records_pass_without_real_requirement(tmp_path: Path):
    path = write_records(tmp_path, [placeholder_record()])
    completed = run_cli(path)
    assert completed.returncode == 0
    assert "no scored records yet" in completed.stdout


def test_placeholder_records_fail_with_require_real_records(tmp_path: Path):
    path = write_records(tmp_path, [placeholder_record()])
    completed = run_cli(path, "--require-real-records")
    assert completed.returncode != 0
    assert "No scored image-output records exist" in completed.stdout


def test_scored_record_with_dicts_and_lists_passes_without_type_error(tmp_path: Path):
    path = write_records(tmp_path, [scored_record()])
    completed = run_cli(path)
    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert "1 scored record" in completed.stdout


def test_scored_record_missing_model_version_fails():
    record = scored_record()
    record["model_version"] = "unknown"
    errors = check_image_output_records.validate_record(record)
    assert any("model_version" in error for error in errors)


def test_scored_record_failed_task_gate_fails():
    record = scored_record()
    record["task_gate_results"]["text_accuracy"] = False
    errors = check_image_output_records.validate_record(record)
    assert any("text_accuracy" in error for error in errors)


def test_scored_record_task_gate_must_match_positive_image_score():
    record = scored_record()
    record["image_score"]["text_accuracy"] = 0
    record["final_score"] = 13
    errors = check_image_output_records.validate_record(record)
    assert any("positive image_score" in error for error in errors)


def test_scored_record_missing_local_output_path_fails():
    record = scored_record()
    record["output_image_path"] = "evals/outputs/missing/output.png"
    errors = check_image_output_records.validate_record(record)
    assert any("output_image_path" in error for error in errors)


def test_scored_record_below_final_score_threshold_fails():
    record = scored_record()
    record["image_score"] = {
        "text_accuracy": 1,
        "text_layout_legibility": 1,
        "subject_fidelity": 1,
        "composition_match": 1,
    }
    record["final_score"] = 4
    record["max_score"] = 24
    errors = check_image_output_records.validate_record(record)
    assert any("below gate" in error for error in errors)


def test_scored_record_final_score_must_match_image_score_sum():
    record = scored_record()
    record["final_score"] = 14
    errors = check_image_output_records.validate_record(record)
    assert any("numeric image_score sum" in error for error in errors)


def test_scored_record_image_score_rejects_invalid_dimension_value():
    record = scored_record()
    record["image_score"]["text_accuracy"] = 3
    errors = check_image_output_records.validate_record(record)
    assert any("must be 0, 1, 2" in error for error in errors)


def test_scored_record_image_score_rejects_unhashable_dimension_value():
    record = scored_record()
    record["image_score"]["text_accuracy"] = {"score": 2}
    errors = check_image_output_records.validate_record(record)
    assert any("must be 0, 1, 2" in error for error in errors)


def test_require_real_records_requires_named_cases(tmp_path: Path):
    path = write_records(tmp_path, [scored_record()])
    completed = run_cli(path, "--require-real-records")
    assert completed.returncode != 0
    assert "Missing required scored image-output cases" in completed.stdout
